"""Generate SigGolfCandidate/Sign/PackData.lean: the pack source table (from work/py/gen.py)."""
import sys, os
sys.path.insert(0, '/root/siggolf/work/py')
import gen
OUT = os.path.dirname(os.path.abspath(__file__))
src = gen.pack_sources()
tab = []
for D, lo, hi in src:
    if hi is None:
        tab.append((2, lo, 0))
    elif hi == lo + 4 and lo % 8 == 0:
        tab.append((0, lo, hi))
    else:
        tab.append((1, lo, hi))
L = ['-- Generated by SigGolfCandidate/Sign/gen_pack.py. Do not edit.',
     'import SigGolfCandidate.Sign.Code', '',
     'namespace SigGolfCandidate.Sign',
     'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '',
     
     '/-- For each signature dword `SIG + 2480 + 8 j`: (kind, lo, hi) stage addresses of its 4-byte',
     'halves (kind 0: one `ld` of `lo`; 1: two `lwu`; 2: last dword, one `lwu`). -/',
     'def packTab : List (Nat × Nat × Nat) := [']
for i in range(0, len(tab), 8):
    L.append('  ' + ', '.join('(%d, %d, %d)' % e for e in tab[i:i+8]) + (',' if i + 8 < len(tab) else ']'))
L += ['',
      '/-- `LWU` as the executor evaluates it. -/',
      'def lwuW (x : Word) (bo : Nat) : Word := LoadKind.fromWord .wu x bo', '',
      '/-- The dword the pack writes for a table entry. -/',
      'def packDW (t : MachineState) : Nat × Nat × Nat → Word',
      '  | (0, lo, _) => t.getMem (BitVec.ofNat 64 lo)',
      '  | (1, lo, hi) => lwuW (t.getMem (alignToDword (BitVec.ofNat 64 lo))) (byteOffset (BitVec.ofNat 64 lo)) +',
      '      lwuW (t.getMem (alignToDword (BitVec.ofNat 64 hi))) (byteOffset (BitVec.ofNat 64 hi)) <<< ((32#64).toNat % 64)',
      '  | (_, lo, _) => lwuW (t.getMem (alignToDword (BitVec.ofNat 64 lo))) (byteOffset (BitVec.ofNat 64 lo))',
      '', 'end SigGolfCandidate.Sign', '']
open(os.path.join(OUT, 'PackData.lean'), 'w').write('\n'.join(L))
print(len(tab), sum(1 for e in tab if e[0] == 0), sum(1 for e in tab if e[0] == 1))
