"""Generate SigGolfCandidate/Sign/Code.lean (segment table of the sign image) and
Blocks*.lean (one sym_block per segment) from work/py/out/sign.lst."""
import re, os
LST = '/root/siggolf/work/py/out/sign.lst'
OUT = os.path.dirname(os.path.abspath(__file__))
ins, labels = [], {}
for line in open(LST):
    m = re.match(r'^([A-Za-z_0-9]+):\s*$', line)
    if m:
        labels.setdefault(len(ins), []).append(m.group(1)); continue
    m = re.match(r'^\s+(\d+) ([0-9a-f]{8})  (\S+)(.*)$', line)
    if m:
        assert int(m.group(1)) == len(ins)
        ins.append((m.group(2), m.group(3), m.group(4).strip()))
N = len(ins)
segs = []   # (start, end exclusive)
cur = 0
CH = 10   # pack groups (of 8 dwords) per pack chunk
def splits_at(i):
    return i in labels and not any(l.startswith('pack_') and int(l[5:]) % CH != 0 for l in labels[i])
for i, (w, mn, ops) in enumerate(ins):
    if i > cur and splits_at(i):
        segs.append((cur, i)); cur = i
    if mn in ('beq', 'bne', 'blt', 'bge', 'bltu', 'bgeu', 'jal', 'ecall', 'jalr'):
        segs.append((cur, i + 1)); cur = i + 1
if cur < N:
    segs.append((cur, N))
assert segs[0][0] == 0 and all(segs[k][1] == segs[k+1][0] for k in range(len(segs)-1)) and segs[-1][1] == N
def name(k): return 'seg%d' % segs[k][0]
L = ['-- Generated by SigGolfCandidate/Sign/gen_code.py from work/py/out/sign.lst. Do not edit.',
     'import SigGolfCandidate.Sign.Base', 'import SigGolfCandidate.Submission', '',
     'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '',
     'set_option maxRecDepth 16384', '']
for k, (a, b) in enumerate(segs):
    lab = ','.join(sum((labels.get(i, []) for i in range(a, b)), []))
    L.append('/-- instructions %d .. %d%s: %s -/' % (a, b - 1, (' (' + lab + ')') if lab else '',
             '; '.join(ins[i][1] + ' ' + ins[i][2] for i in range(a, min(b, a + 6))) + (' ...' if b - a > 6 else '')))
    L.append('def %s : List (BitVec 32) := [%s]' % (name(k), ', '.join('0x%s#32' % ins[i][0] for i in range(a, b))))
L.append('')
L.append('/-- Segment table of the sign image. -/')
L.append('def L : Rv.Layout := [' + ', '.join('(%d, %s)' % (a, name(k)) for k, (a, b) in enumerate(segs)) + ']')
L.append('''
theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The sign image. -/
abbrev image : Image := Images.signImage

theorem image_eq : submission.image .sign = image := rfl

set_option maxHeartbeats 4000000 in
theorem code_eq : image.code = layoutCode L := by decide +kernel
''')
for k, (a, b) in enumerate(segs):
    L.append('theorem codeAt_%d : CodeAt image (pcOf %d) %s :=\n  codeAt_layout code_eq layout_ok (i := %d) (by kernel_rfl) (by decide)' % (a, a, name(k), k))
L += ['', 'end SigGolfCandidate.Sign', '']
open(os.path.join(OUT, 'Code.lean'), 'w').write('\n'.join(L))
# blocks: main program (non-pack) and pack in separate files
main = [(k, s) for k, s in enumerate(segs) if s[0] < min(i for i, ls in labels.items() if 'pack_0' in ls)]
pack = [(k, s) for k, s in enumerate(segs) if (k, s) not in main]
def blocks(fn, lst, header):
    B = ['-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.', 'import SigGolfCandidate.Sign.Code', '',
         'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '', header, '']
    for k, (a, b) in lst:
        B.append('sym_block blk%d := symRun { noAlias := true } %s (pcOf %d) %d' % (a, name(k), a, b - a + 1))
    B += ['', 'end SigGolfCandidate.Sign', '']
    open(os.path.join(OUT, fn), 'w').write('\n'.join(B))
blocks('Blocks.lean', main, '/-! Symbolic blocks of the sign program (before the pack). -/')
# pack chunks: one file each (kernel memory accumulates within a file)
pack_chunks = [(k, s) for k, s in pack if s[0] < N - 3]
halt = [(k, s) for k, s in pack if s[0] >= N - 3]
assert len(halt) == 1
D = 0x2650 + 2480
f = 0
chunk_info = []
for j, (k, (a, b)) in enumerate(pack_chunks):
    c = sum(1 for i in range(a, b) if ins[i][1] == 'sd')
    n = b - a
    B = ['-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.', 'import SigGolfCandidate.Sign.PackStep', '',
         'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '',
         '/-! Pack chunk %d: instructions %d .. %d, signature dwords %d .. %d. -/' % (j, a, b - 1, f, f + c - 1), '',
         'set_option maxRecDepth 100000', '',
         'sym_block blk%d := symRun { noAlias := true } %s (pcOf %d) %d' % (a, name(k), a, n + 1), '',
         'kernel_theorem blk%d_pc : ∀ t : MachineState, (blk%d.res.toState t).pc = pcOf %d' % (a, a, b),
         'kernel_theorem blk%d_addrs : ∀ t : MachineState, blk%d.res.st.mem.map (fun p => p.1.eval t) =' % (a, a),
         '    ((List.range %d).map (fun i => BitVec.ofNat 64 (packD + 8 * %d + 8 * i))).reverse' % (c, f),
         'kernel_theorem blk%d_words : ∀ t : MachineState,' % a,
         '    (blk%d.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * %d)) %d =' % (a, f, c),
         '      ((packTab.drop %d).take %d).map (packDW t)' % (f, c), '',
         'theorem packStep_%d : PackStep %d %d %d %d %d :=' % (a, a, b, f, c, n),
         '  packStep_of blk%d codeAt_%d rfl blk%d_pc rfl rfl blk%d_words blk%d_addrs (by norm_num)' % (a, a, a, a, a),
         '', 'end SigGolfCandidate.Sign', '']
    open(os.path.join(OUT, 'PackC%d.lean' % j), 'w').write('\n'.join(B))
    chunk_info.append((a, b, f, c, n))
    f += c
assert f == 660
R = ['-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.'] + \
    ['import SigGolfCandidate.Sign.PackC%d' % j for j in range(len(pack_chunks))] + ['',
     'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '',
     '/-- The whole pack (instructions %d .. %d). -/' % (pack_chunks[0][1][0], pack_chunks[-1][1][1] - 1),
     'theorem pack_run : PackStep %d %d 0 660 %d :=' % (pack_chunks[0][1][0], pack_chunks[-1][1][1], sum(x[4] for x in chunk_info))]
e = 'packStep_%d' % chunk_info[0][0]
for (a, b, f2, c, n) in chunk_info[1:]:
    e = '(%s.comp packStep_%d (by norm_num))' % (e, a)
R += ['  ' + e, '']
k, (a, b) = halt[0]
R += ['-- The final HALT.', 'sym_block blk%d := symRun { noAlias := true } %s (pcOf %d) %d' % (a, name(k), a, b - a + 1),
      '', 'end SigGolfCandidate.Sign', '']
open(os.path.join(OUT, 'PackRun.lean'), 'w').write('\n'.join(R))
print('pack chunks', chunk_info)
print(len(segs), 'segments;', len(main), 'main;', len(pack), 'pack')
for k, (a, b) in main:
    print(a, b, labels.get(a, ''), ins[b-1][1], ins[b-1][2])
