"""Emit the four images, sizes, layout and label tables as Lean (out/Images.lean).

usage: python3 export_lean.py [perm|copy]
"""
import os, sys
import gen

mode = sys.argv[1] if len(sys.argv) > 1 else 'perm'
images, asms, vg = gen.build_all(mode)
out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out')
os.makedirs(out_dir, exist_ok=True)

L = ['-- Generated by work/py/export_lean.py (witness mode: %s). Do not edit.' % mode,
     'import SigGolf', '', 'set_option maxRecDepth 8192', '', 'namespace SphincsGolf', 'open SigGolf', '',
     'def signatureBytes : Nat := %d' % gen.S_BYTES,
     'def witnessBytes : Nat := %d' % gen.W_BYTES, '',
     '/-- message, secretKey, publicKey, cache, signature, witness -/',
     'def layout : Layout := ⟨0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x⟩' % (
         gen.MSG, gen.SK, gen.PK, gen.CACHE, gen.SIG, gen.WIT), '',
     '/-- Scratch buffers (byte addresses), see PROGRAMS.md. -/']
for name in ['DB', 'CB', 'EB', 'EO', 'DO', 'FO', 'NB', 'RB2', 'LB', 'RB', 'PB', 'DIG', 'US', 'FA', 'TA', 'DIG8', 'STG']:
    L.append('def addr%s : Nat := 0x%x' % (name, getattr(gen, name)))
L.append('')
for phase in ['keygen', 'sign', 'expand', 'verify']:
    code, data = images[phase]
    CH = 256
    names = []
    for c0 in range(0, len(code), CH):
        part = code[c0:c0 + CH]
        nm = '%sCode_%d' % (phase, c0 // CH)
        names.append(nm)
        L.append('/-- instructions %d .. %d -/' % (c0, c0 + len(part) - 1))
        L.append('def %s : List (BitVec 32) := [' % nm)
        for i in range(0, len(part), 8):
            L.append('  ' + ', '.join('0x%08x' % w for w in part[i:i + 8]) + (',' if i + 8 < len(part) else ']'))
    L.append('def %sCode : List (BitVec 32) :=' % phase)
    L.append('  ' + ' ++\n  '.join(names))
    L.append('def %sData : List (BitVec 8) := [%s]' % (phase, ', '.join('0x%02x' % b for b in data)))
    L.append('def %sImage : Riscv.Image := ⟨%sCode, %sData⟩' % (phase, phase, phase))
    L.append('')
L += ['def submission : Submission where',
      '  sizes := ⟨signatureBytes, witnessBytes⟩',
      '  layout := layout',
      '  image',
      '    | .keygen => keygenImage',
      '    | .sign => signImage',
      '    | .expand => expandImage',
      '    | .verify => verifyImage', '']
L.append('/-! Label tables: label name -> instruction index (pc = 0x1000 + 4 * index). -/')
for phase in ['keygen', 'sign', 'expand', 'verify']:
    labs = sorted(asms[phase].labels.items(), key=lambda kv: (kv[1], kv[0]))
    names = []
    for c0 in range(0, len(labs), 256):
        part = labs[c0:c0 + 256]
        nm = '%sLabels_%d' % (phase, c0 // 256)
        names.append(nm)
        L.append('def %s : List (String × Nat) := [' % nm)
        for j, (n, k) in enumerate(part):
            L.append('  ("%s", %d)%s' % (n, k, ',' if j + 1 < len(part) else ']'))
    L.append('def %sLabels : List (String × Nat) :=' % phase)
    L.append('  ' + ' ++\n  '.join(names))
    L.append('')
L += ['end SphincsGolf', '']
path = os.path.join(out_dir, 'Images.lean')
with open(path, 'w') as f:
    f.write('\n'.join(L))
# human-readable listings alongside
for phase in ['keygen', 'sign', 'expand', 'verify']:
    with open(os.path.join(out_dir, phase + '.lst'), 'w') as f:
        f.write(asms[phase].listing() + '\n')
print('wrote', path, {p: len(images[p][0]) for p in images})
