import re
src=open("/root/siggolf/work/rv/SigGolfCandidate/Images.lean").read()
m=re.search(r"def expandCode_0 : List \(BitVec 32\) := \[(.*?)\]",src,re.S)
words=[w.strip() for w in m.group(1).replace("\n"," ").split(",")]
assert len(words)==167
loop=["0x00036183","0x0033a023","0x00430313","0x00438393","0xfff40413","0xfe0416e3"]
pres=[(0,5),(11,4)]+[(21+11*j,5) for j in range(13)]
assert pres[-1][0]==153
copies=[(0x2650,0x800,620)]
for lay in range(7):
    copies.append((0x2650+2480+756*lay,0x800+7728+4*lay,1))
    copies.append((0x2650+2480+756*lay+4,0x800+2480+752*lay,184 if lay==6 else 188))
assert len(copies)==15
L=[]
for k,(o,n) in enumerate(pres):
    assert words[o+n:o+n+6]==loop, k
    L.append((o,f"pre{k}")); L.append((o+n,"loopCode"))
L.append((164,"fin"))
out=[]
out.append('''import SigGolfCandidate.Expand.Loop
import SigGolfCandidate.Submission

/-!
# `expand`: the program as 15 stages (prelude + copy loop) and a HALT block

Generated by `SigGolfCandidate/Expand/gen_expand.py` (segment table of `Images.expandCode`).
-/

namespace SigGolfCandidate.Expand
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv SigGolfCandidate.Mem

set_option maxRecDepth 8192
''')
for k,(o,n) in enumerate(pres):
    out.append(f"def pre{k} : List (BitVec 32) := [{', '.join(words[o:o+n])}]")
out.append(f"def fin : List (BitVec 32) := [{', '.join(words[164:167])}]")
out.append("\n/-- Segment table. -/\ndef L : Rv.Layout := [" + ", ".join(f"({o}, {nm})" for o,nm in L) + "]")
out.append('''
theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The expand image. -/
abbrev image : Image := submission.image .expand

theorem code_eq : image.code = layoutCode L := by decide +kernel
''')
for i,(o,nm) in enumerate(L):
    out.append(f"theorem codeAt_{i} : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * {o})) {nm} :=\n  codeAt_layout code_eq layout_ok (i := {i}) (by kernel_rfl) (by decide)")
out.append("")
for k,(o,n) in enumerate(pres):
    out.append(f"sym_block run{k} := symRun {{}} pre{k} (BitVec.ofNat 64 (0x1000 + 4 * {o})) 10")
out.append(f"sym_block runFin := symRun {{}} fin (BitVec.ofNat 64 (0x1000 + 4 * 164)) 10")
out.append("")
out.append("/-- The fifteen copies `(src, dst, words)` in program order. -/\ndef copies : List (Nat × Nat × Nat) := [" + ", ".join(f"({a}, {b}, {c})" for a,b,c in copies) + "]")
out.append("")
for k,(o,n) in enumerate(pres):
    a,b,c=copies[k]
    out.append(f"""theorem stage{k} (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * {o}))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run{k}.res.steps + {c} * 6) (run{k}.res.cycles + {c} * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * {o+n}) + 24 ∧ BytesEq u (applyCopy ({a}, {b}, {c}) f) :=
  stage run{k} codeAt_{2*k} rfl rfl rfl rfl rfl rfl codeAt_{2*k+1} (by decide) t htpc f hf
""")
open("/root/siggolf/work/rv/SigGolfCandidate/Expand/Stages.lean","w").write("\n".join(out)+"\n\nend SigGolfCandidate.Expand\n")

# ---- chain ----
o=[]
o.append('''import SigGolfCandidate.Expand.Stages

/-!
# `expand`: composition of the stages (generated by `SigGolfCandidate/Expand/gen_expand.py`)
-/

namespace SigGolfCandidate.Expand
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv SigGolfCandidate.Mem

/-- The whole program up to the final `ecall`: 11710 steps and cycles, `t0 = 1`, `a0 = 0`, and
the byte view of memory is the fifteen copies applied to the initial one. -/
theorem expand_steps (s : MachineState) (hpc : s.pc = 0x1000) :
    ∃ u, Steps image s 11710 11710 u ∧ fetch image u = some (.base .ECALL) ∧
      u.getReg .x5 = 1 ∧ u.getReg .x10 = 0 ∧
      BytesEq u (applyCopies copies (fun a => s.getByte (BitVec.ofNat 64 a))) := by''')
o.append("  obtain ⟨u0, st0, pc0, b0⟩ := stage0 s (by rw [hpc]; rfl) _ (fun a _ => rfl)")
for k in range(1,15):
    o.append(f"  obtain ⟨u{k}, st{k}, pc{k}, b{k}⟩ := stage{k} u{k-1} (by rw [pc{k-1}]; decide) _ b{k-1}")
o.append('''  have hpcF : u14.pc = BitVec.ofNat 64 (0x1000 + 4 * 164) := by rw [pc14]; decide
  have hobl : runFin.res.obligs u14 := by simp only [runFin.res, rv_simp]
  have stF := symRun_sound runFin codeAt_30 u14 hpcF hobl''')
chain="st0"
for k in range(1,15): chain=f"({chain}.trans st{k})"
o.append(f"  refine ⟨_, Steps.of_eq ({chain}.trans stF) rfl rfl,\n    symRun_ecall runFin codeAt_30 u14 hobl rfl, by simp [runFin.res, rv_simp], by simp [runFin.res, rv_simp], ?_⟩")
o.append('''  intro a ha
  have h := b14 a ha
  simp only [MachineState.getByte, Result.toState_getMem, runFin.res, memEval_nil] at h ⊢
  exact h''')
# coverage
covs=[]
covs.append(("i < 2480", 0))
for lay in range(7):
    covs.append((f"(2480 + 752 * {lay} ≤ i ∧ i < 2480 + 752 * {lay} + 4 * {184 if lay==6 else 188})", 2+2*lay))
    covs.append((f"(7728 + 4 * {lay} ≤ i ∧ i < 7728 + 4 * {lay} + 4)", 1+2*lay))
o.append('''
/-- Every witness byte is the destination of exactly the copy that reads its `witnessSrc`. -/
theorem copies_cover (i : Nat) (hi : i < 7756) :
    ∃ c ∈ copies, c.2.1 ≤ 0x800 + i ∧ 0x800 + i < c.2.1 + 4 * c.2.2 ∧
      0x800 + i - c.2.1 + c.1 = 0x2650 + Ref.witnessSrc i := by
  unfold Ref.witnessSrc Ref.sigLayerOff Ref.witLayerOff Ref.witCounters''')
o.append("  rcases (show " + " ∨ ".join(c for c,_ in covs) + " by omega) with " + " | ".join("h" for _ in covs))
for _,idx in covs:
    a,b,c=copies[idx]
    o.append(f"  · refine ⟨({a}, {b}, {c}), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega")
open("/root/siggolf/work/rv/SigGolfCandidate/Expand/Chain.lean","w").write("\n".join(o)+"\n\nend SigGolfCandidate.Expand\n")
