import SigGolfCandidate.SphincsCacheMacCompact
import SigGolfCandidate.SphincsCacheRequestSplit
import SigGolfCandidate.SphincsAlignedQuery

/-! The all-failure MAC test plan generated by a capped organizer attacker.
Canonical signing is an opaque service, and non-byte-aligned direct hash queries
are answered by the independent part of the split random oracle. -/

namespace SigGolfCandidate.SphincsTypedInteractionPlan
open SigGolf OracleComp OracleSpec SphincsSecurity
open SigGolfCandidate.SphincsCacheMacTypedGame
open SigGolfCandidate.SphincsCacheMacFiniteDomain
open SigGolfCandidate.SphincsCacheRequestSplit
open SigGolfCandidate.SphincsAlignedQuery
open SigGolfCandidate.SphincsCacheMacTypedTrace
open SigGolfCandidate.SphincsCacheMacTypedStop
open SigGolfCandidate.SphincsCacheMacRealIdeal
open SigGolfCandidate.SphincsCacheMacStoppedActual
open SigGolfCandidate.SphincsCacheMacCompiledGame
open SigGolfCandidate.SphincsSeededNoMacQueries
open SigGolfCandidate.SphincsMaskedCacheProgramming
set_option backward.isDefEq.respectTransparency false

noncomputable def plan
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (Q : Nat) : Nat → adversary.State → Nat →
      OracleComp (TypedAttackWorld (ciphertext canonical)) Unit
  | 0, _, _ => pure ()
  | rounds + 1, state, count =>
      match adversary.step state with
      | .submit _ => pure ()
      | .hash input resume =>
          if h : input.1 % 8 = 0 then do
            let answer ← liftM ((TypedAttackWorld (ciphertext canonical)).query
              (.inl (.inl (.inr (alignedInput input h)))))
            plan adversary canonical nonalignedAnswer wire Q rounds
              (resume answer) count
          else
            plan adversary canonical nonalignedAnswer wire Q rounds
              (resume (nonalignedAnswer ⟨input, h⟩)) count
      | .sample n resume => do
          let answer ← liftM ((TypedAttackWorld (ciphertext canonical)).query
            (.inl (.inl (.inl n))))
          plan adversary canonical nonalignedAnswer wire Q rounds
            (resume answer) count
      | .step next =>
          plan adversary canonical nonalignedAnswer wire Q rounds next count
      | .sign request resume =>
          if count < Q ∧ count < SigGolf.LIFETIME then
            if hprefix : authPrefix request.cache = authPrefix canonical then
              if macTag request.cache = macTag canonical then do
                let response ← liftM ((TypedAttackWorld (ciphertext canonical)).query
                  (.inl (.inr request.message)))
                plan adversary canonical nonalignedAnswer wire Q rounds
                  (resume (response.map wire)) (count + 1)
              else
                plan adversary canonical nonalignedAnswer wire Q rounds
                  (resume none) (count + 1)
            else do
              let _ ← liftM ((TypedAttackWorld (ciphertext canonical)).query
                (.inr (⟨ciphertext request.cache,
                  ciphertext_ne_of_auth_prefix_ne request.cache canonical hprefix⟩,
                  macTag request.cache)))
              plan adversary canonical nonalignedAnswer wire Q rounds
                (resume none) (count + 1)
          else pure ()

theorem plan_attempts_le
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (Q rounds : Nat) (state : adversary.State) (count : Nat)
    (world : QueryImpl SphincsCacheMacThreeService.OuterWorld Id)
    (hcount : count ≤ Q) :
    (typedFailureTrace world
      (plan adversary canonical nonalignedAnswer wire Q rounds state count)).length
      ≤ Q - count := by
  induction rounds generalizing state count with
  | zero => simp [plan, typedFailureTrace]
  | succ rounds ih =>
      cases haction : adversary.step state with
      | submit candidate => simp [plan, haction, typedFailureTrace]
      | hash input resume =>
          by_cases halign : input.1 % 8 = 0
          · simp only [plan, haction, halign, ↓reduceDIte,
              typedFailureTrace, OracleComp.construct_query_bind]
            exact ih (resume (world (.inl (.inr (alignedInput input halign)))))
              count hcount
          · simpa [plan, haction, halign] using
              ih (resume (nonalignedAnswer ⟨input, halign⟩)) count hcount
      | sample n resume =>
          simp only [plan, haction, typedFailureTrace,
            OracleComp.construct_query_bind]
          exact ih (resume (world (.inl (.inl n)))) count hcount
      | step next =>
          simpa [plan, haction] using ih next count hcount
      | sign request resume =>
          by_cases hcap : count < Q ∧ count < SigGolf.LIFETIME
          · by_cases hprefix : authPrefix request.cache = authPrefix canonical
            · by_cases htag : macTag request.cache = macTag canonical
              · simp [plan, haction, hcap, hprefix, htag, typedFailureTrace]
                have hnext := ih (resume ((world (.inr request.message)).map wire))
                  (count + 1) (by omega)
                change (typedFailureTrace world
                  (plan adversary canonical nonalignedAnswer wire Q rounds
                    (resume ((world (.inr request.message)).map wire))
                    (count + 1))).length ≤ Q - count
                omega
              · simpa [plan, haction, hcap, hprefix, htag] using
                  (ih (resume none) (count + 1) (by omega)).trans
                    (by omega : Q - (count + 1) ≤ Q - count)
            · simp [plan, haction, hcap, hprefix, typedFailureTrace]
              have hnext := ih (resume none) (count + 1) (by omega)
              change (List.cons
                (⟨ciphertext request.cache,
                  ciphertext_ne_of_auth_prefix_ne request.cache canonical hprefix⟩,
                  macTag request.cache)
                (typedFailureTrace world
                  (plan adversary canonical nonalignedAnswer wire Q rounds
                    (resume none) (count + 1)))).length ≤ Q - count
              simp only [List.length_cons]
              omega
          · simp [plan, haction, hcap, typedFailureTrace]

theorem plan_support_attempts_le
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (Q rounds : Nat) (state : adversary.State) (count : Nat)
    (hcount : count ≤ Q) :
    ∀ result ∈ support
      (typedFailureProgram
        (plan adversary canonical nonalignedAnswer wire Q rounds state count)),
      result.2.length ≤ Q - count := by
  induction rounds generalizing state count with
  | zero => simp [plan, typedFailureProgram]
  | succ rounds ih =>
      cases haction : adversary.step state with
      | submit candidate => simp [plan, haction, typedFailureProgram]
      | hash input resume =>
          by_cases halign : input.1 % 8 = 0
          · intro result hmem
            simp only [plan, haction, halign, ↓reduceDIte] at hmem
            rw [typedFailureProgram_query_bind] at hmem
            simp only [support_bind, Set.mem_iUnion] at hmem
            obtain ⟨answer, _, hnext⟩ := hmem
            exact ih (resume answer) count hcount result hnext
          · simpa [plan, haction, halign] using
              ih (resume (nonalignedAnswer ⟨input, halign⟩)) count hcount
      | sample n resume =>
          intro result hmem
          simp only [plan, haction] at hmem
          rw [typedFailureProgram_query_bind] at hmem
          simp only [support_bind, Set.mem_iUnion] at hmem
          obtain ⟨answer, _, hnext⟩ := hmem
          exact ih (resume answer) count hcount result hnext
      | step next =>
          simpa [plan, haction] using ih next count hcount
      | sign request resume =>
          by_cases hcap : count < Q ∧ count < SigGolf.LIFETIME
          · by_cases hprefix : authPrefix request.cache = authPrefix canonical
            · by_cases htag : macTag request.cache = macTag canonical
              · intro result hmem
                simp only [plan, haction, hcap, ↓reduceIte, hprefix,
                  ↓reduceDIte, htag] at hmem
                simp only [and_self, ↓reduceIte] at hmem
                rw [typedFailureProgram_query_bind] at hmem
                simp only [support_bind, Set.mem_iUnion] at hmem
                obtain ⟨answer, _, hnext⟩ := hmem
                have hlen := ih (resume (answer.map wire)) (count + 1)
                  (by omega) result hnext
                omega
              · simpa [plan, haction, hcap, hprefix, htag] using
                  (fun result hmem =>
                    (ih (resume none) (count + 1) (by omega) result hmem).trans
                      (by omega : Q - (count + 1) ≤ Q - count))
            · intro result hmem
              simp only [plan, haction, hcap, hprefix,
                ↓reduceDIte] at hmem
              simp only [and_self, ↓reduceIte] at hmem
              rw [typedFailureProgram_query_bind] at hmem
              simp only [support_bind, Set.mem_iUnion, support_pure,
                Set.mem_singleton_iff] at hmem
              obtain ⟨tail, htail, hresult⟩ := hmem
              subst result
              have hlen := ih (resume none) (count + 1) (by omega) tail htail
              simp only [List.length_cons]
              omega
          · simp [plan, haction, hcap, typedFailureProgram]

theorem stopped_plan_support_attempts_le
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (seed : MasterSeed) (Q rounds : Nat)
    (state : adversary.State) (count : Nat) (hcount : count ≤ Q) :
    ∀ result ∈ support
      (typedFailureProgram (stopBeforeTyped seed
        (plan adversary canonical nonalignedAnswer wire Q rounds state count))),
      result.2.length ≤ Q - count := by
  induction rounds generalizing state count with
  | zero => simp [plan, stopBeforeTyped, typedFailureProgram]
  | succ rounds ih =>
      cases haction : adversary.step state with
      | submit candidate => simp [plan, haction, stopBeforeTyped, typedFailureProgram]
      | hash input resume =>
          by_cases halign : input.1 % 8 = 0
          · intro result hmem
            simp only [plan, haction, halign, ↓reduceDIte] at hmem
            rw [stopBeforeTyped_query_bind] at hmem
            by_cases hhit : SphincsCacheMacThreeService.attackerDirectSeedHit seed
                (.inl (.inr (alignedInput input halign)))
            · simp [hhit, typedFailureProgram] at hmem
              subst result
              simp
            · simp only [hhit, ↓reduceIte] at hmem
              rw [typedFailureProgram_query_bind] at hmem
              simp only [support_bind, Set.mem_iUnion] at hmem
              obtain ⟨answer, _, hnext⟩ := hmem
              exact ih (resume answer) count hcount result hnext
          · simpa [plan, haction, halign] using
              ih (resume (nonalignedAnswer ⟨input, halign⟩)) count hcount
      | sample n resume =>
          intro result hmem
          simp only [plan, haction] at hmem
          rw [stopBeforeTyped_query_bind] at hmem
          simp only [SphincsCacheMacThreeService.attackerDirectSeedHit,
            ↓reduceIte] at hmem
          rw [typedFailureProgram_query_bind] at hmem
          simp only [support_bind, Set.mem_iUnion] at hmem
          obtain ⟨answer, _, hnext⟩ := hmem
          exact ih (resume answer) count hcount result hnext
      | step next =>
          simpa [plan, haction] using ih next count hcount
      | sign request resume =>
          by_cases hcap : count < Q ∧ count < SigGolf.LIFETIME
          · by_cases hprefix : authPrefix request.cache = authPrefix canonical
            · by_cases htag : macTag request.cache = macTag canonical
              · intro result hmem
                simp only [plan, haction, hcap, ↓reduceIte, hprefix,
                  ↓reduceDIte, htag] at hmem
                simp only [and_self, ↓reduceIte] at hmem
                rw [stopBeforeTyped_query_bind] at hmem
                simp only [SphincsCacheMacThreeService.attackerDirectSeedHit,
                  ↓reduceIte] at hmem
                rw [typedFailureProgram_query_bind] at hmem
                simp only [support_bind, Set.mem_iUnion] at hmem
                obtain ⟨answer, _, hnext⟩ := hmem
                have hlen := ih (resume (answer.map wire)) (count + 1)
                  (by omega) result hnext
                omega
              · simpa [plan, haction, hcap, hprefix, htag] using
                  (fun result hmem =>
                    (ih (resume none) (count + 1) (by omega) result hmem).trans
                      (by omega : Q - (count + 1) ≤ Q - count))
            · intro result hmem
              simp only [plan, haction, hcap, hprefix, ↓reduceDIte] at hmem
              simp only [and_self, ↓reduceIte] at hmem
              rw [stopBeforeTyped_query_bind] at hmem
              rw [typedFailureProgram_query_bind] at hmem
              simp only [support_bind, Set.mem_iUnion, support_pure,
                Set.mem_singleton_iff] at hmem
              obtain ⟨tail, htail, hresult⟩ := hmem
              subst result
              have hlen := ih (resume none) (count + 1) (by omega) tail htail
              simp only [List.length_cons]
              omega
          · simp [plan, haction, hcap, stopBeforeTyped, typedFailureProgram]

theorem stopped_plan_interpreted_attempts_le
    {σ : Type} (impl : QueryImpl SphincsCacheMacThreeService.OuterWorld
      (StateT σ ProbComp)) (initial : σ)
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (seed : MasterSeed) (Q rounds : Nat)
    (state : adversary.State) (count : Nat) (hcount : count ≤ Q) :
    ∀ result ∈ support
      ((simulateQ impl
        (typedFailureProgram (stopBeforeTyped seed
          (plan adversary canonical nonalignedAnswer wire Q rounds state count)))).run'
          initial),
      result.2.length ≤ Q - count := by
  intro result hmem
  exact stopped_plan_support_attempts_le adversary canonical nonalignedAnswer
    wire seed Q rounds state count hcount result
      (support_simulateQ_run'_subset impl _ initial hmem)

theorem plan_real_first_hit_le
    (adversary : SigGolf.Adversary SphincsSubmission.submission.sizes)
    (canonical : SigGolf.Cache)
    (nonalignedAnswer : NonalignedQuery → BitVec 256)
    (wire : SphincsSecurity.Signature →
      SigGolf.Bytes SphincsSubmission.submission.sizes.signature)
    (secretKey : Seeded.SecretKey)
    (material : Seeded.KeyMaterial) (seed : MasterSeed)
    (pads : List (BitVec 32 × HashOutput))
    (macAnswer : HashOutput) (Q rounds : Nat)
    (state : adversary.State) :
    Pr[fun result => result.2 = true |
      StateT.run' (simulateQ romImpl
        (compiledFailureFlag secretKey
          (stopBeforeAttack seed
            (encodeTyped material.1 seed (ciphertext canonical)
              (plan adversary canonical nonalignedAnswer wire Q rounds state 0)))))
        (maskedMaterialCache material seed pads
          (List.ofFn (ciphertext canonical)) macAnswer)] ≤
      Q * (Fintype.card Digest : ENNReal)⁻¹ := by
  apply real_first_hit_le_of_attempts secretKey material seed pads
    (ciphertext canonical) macAnswer
    (plan adversary canonical nonalignedAnswer wire Q rounds state 0) Q
  intro result hmem
  exact stopped_plan_interpreted_attempts_le
    (romImpl + canonicalSigner secretKey)
    (maskedMaterialCache material seed pads
      (List.ofFn (ciphertext canonical)) macAnswer)
    adversary canonical nonalignedAnswer wire seed Q rounds state 0 (by omega)
    result hmem

end SigGolfCandidate.SphincsTypedInteractionPlan

/-- info: 'SigGolfCandidate.SphincsTypedInteractionPlan.plan_attempts_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms SigGolfCandidate.SphincsTypedInteractionPlan.plan_attempts_le

/-- info: 'SigGolfCandidate.SphincsTypedInteractionPlan.plan_support_attempts_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms SigGolfCandidate.SphincsTypedInteractionPlan.plan_support_attempts_le

/-- info: 'SigGolfCandidate.SphincsTypedInteractionPlan.stopped_plan_support_attempts_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms SigGolfCandidate.SphincsTypedInteractionPlan.stopped_plan_support_attempts_le

/-- info: 'SigGolfCandidate.SphincsTypedInteractionPlan.stopped_plan_interpreted_attempts_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms SigGolfCandidate.SphincsTypedInteractionPlan.stopped_plan_interpreted_attempts_le

/-- info: 'SigGolfCandidate.SphincsTypedInteractionPlan.plan_real_first_hit_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms SigGolfCandidate.SphincsTypedInteractionPlan.plan_real_first_hit_le
