import SigGolfCandidate.Images

/-!
# The sig.golf submission (SPHINCS-golf, witness mode `perm`)

Sizes `S = W = 7756`, the shared layout of `PROGRAMS.md` (message `0x40`, secret key `0x80`,
public key `0xA0`, cache `0x44A0`, signature `0x2650`, witness `0x800`) and the four images
generated by `work/py/gen.py` (`SigGolfCandidate/Images.lean`).
-/

namespace SigGolfCandidate
open SigGolf

/-- The submission value. -/
def submission : Submission where
  sizes := ⟨7756, 7756⟩
  layout := ⟨0x40, 0x80, 0xA0, 0x44A0, 0x2650, 0x800⟩
  image
    | .keygen => Images.keygenImage
    | .sign => Images.signImage
    | .expand => Images.expandImage
    | .verify => Images.verifyImage

theorem submission_eq_images : submission = Images.submission := by
  unfold submission Images.submission; rfl

theorem submission_sizes : submission.sizes = ⟨7756, 7756⟩ := rfl

/-- Static admission (sizes, image-size limits, aligned nonoverlapping buffers). -/
theorem submission_admissible : submission.Admissible := by
  refine ⟨by unfold Sizes.Valid; decide, ?_⟩
  intro phase
  cases phase <;> decide +kernel

end SigGolfCandidate

