import SigGolfCandidate.Rv

/-!
# Demo 1: a 40-instruction straight-line block, proven by reflection

Loads/stores at constant addresses (`0x20060..0x20077`, via `lui/addi`) and relative to the
pointer `x10`, including 32-bit and byte accesses, shifts, comparisons and W-ops.
Instruction list generated by `tools/gen_demos.py` (assembler: `tools/rvasm.py`).
-/

namespace SigGolfCandidate.Rv.Demo1
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

def code : List (BitVec 32) :=
[0x000202b7#32, 0x06028293#32, 0x00053303#32, 0x00853383#32, 0x00730433#32, 0x0082b023#32,
  0x01053483#32, 0x00944633#32, 0x00c2b423#32, 0x0002b683#32, 0x40668733#32, 0x00e53c23#32,
  0x01853783#32, 0xfff00813#32, 0x0102a823#32, 0x0102a883#32, 0x0102e903#32, 0x0112c983#32,
  0x03350023#32, 0x02053a03#32, 0x00439a93#32, 0x002adb13#32, 0x43c85b93#32, 0x017b6c33#32,
  0x7f0c7c93#32, 0x00733d33#32, 0x00082db3#32, 0x00580e1b#32, 0x401e5e9b#32, 0x01de0f3b#32,
  0x03e53423#32, 0x02853f83#32, 0x41ef85b3#32, 0x027300b3#32, 0x010311b3#32, 0x01035233#32,
  0x4040d0b3#32, 0x00126213#32, 0xfff1c193#32, 0x03050513#32]

/-- The image: the block followed by a HALT `ecall`. -/
def image : Image := ⟨code ++ [0x00000073#32], []⟩

theorem codeAt : CodeAt image 0x1000 code :=
  CodeAt.of_append (pre := []) (post := [0x00000073#32]) rfl _ (by decide) (by decide)

-- The executor run, certified by the kernel (one reflection check).
sym_block run := symRun { noAlias := true } code 0x1000 100

example : run.res.steps = 40 ∧ run.res.cycles = 43 ∧ run.res.stop = .endOfCode := by decide

/-- The block lemma, stated about concrete states. -/
theorem spec (s : MachineState) (p : Nat) (hpc : s.pc = 0x1000)
    (hx10 : s.getReg .x10 = BitVec.ofNat 64 p) (hal : p % 8 = 0) (hp : p + 48 ≤ 0x20000) :
    ∃ t, Steps image s 40 43 t ∧
      t.pc = 0x10a0 ∧
      t.getReg .x10 = s.getReg .x10 + 48 ∧
      t.getReg .x11 = 0 ∧
      t.getReg .x15 = s.getMem (s.getReg .x10 + 8) ∧
      t.getReg .x8 = s.getMem (s.getReg .x10) + s.getMem (s.getReg .x10 + 8) ∧
      t.getReg .x30 = 6 ∧
      t.getMem 0x20060 = s.getMem (s.getReg .x10) + s.getMem (s.getReg .x10 + 8) ∧
      t.getMem (s.getReg .x10 + 24) = s.getMem (s.getReg .x10 + 8) ∧
      t.getMem (s.getReg .x10 + 40) = 6 ∧
      -- frame: untouched memory is unchanged
      (∀ a, a.toNat < p → t.getMem a = s.getMem a) := by
  have hobl : run.res.obligs s := by rv_obligs [run.res, hx10]
  refine ⟨_, symRun_sound run codeAt s hpc hobl, ?_⟩
  -- registers and pc: readable forms by `simp only [run.res, rv_simp]`
  refine ⟨by simp only [run.res, rv_simp], by simp only [run.res, rv_simp],
    by simp only [run.res, rv_simp], ?_, by simp only [run.res, rv_simp],
    by simp only [run.res, rv_simp], ?_⟩
  · simp only [run.res, rv_simp]; rw [BitVec.add_comm, BitVec.add_sub_cancel]
  -- memory: reflective reads (`readMem` computed by the kernel), then `rv_simp`
  have r1 := run.res.toState_getMem_of_read s (cfg := { noAlias := true })
    (k := ⟨none, 0x20060⟩) (by sym_eval) (by rv_obligs [run.res, hx10])
  have r2 := run.res.toState_getMem_of_read s (cfg := { noAlias := true })
    (k := ⟨some (.reg .x10), 24⟩) (by sym_eval) (by rv_obligs [run.res, hx10])
  have r3 := run.res.toState_getMem_of_read s (cfg := { noAlias := true })
    (k := ⟨some (.reg .x10), 40⟩) (by sym_eval) (by rv_obligs [run.res, hx10])
  simp only [rv_simp] at r1 r2 r3 ⊢
  refine ⟨r1, by rw [r2, BitVec.add_comm, BitVec.add_sub_cancel], r3, ?_⟩
  -- frame, via `Result.toState_getMem_frame`
  intro a ha
  apply run.res.toState_getMem_frame
  simp only [run.res, rv_simp, List.mem_cons, List.not_mem_nil, forall_eq_or_imp, or_false,
    forall_eq, ne_eq, BitVec.toNat_eq, BitVec.toNat_add, BitVec.toNat_ofNat, hx10]
  and_intros <;> omega

/-- The same block lemma in `execute` form (composition law). -/
theorem spec_execute (s : MachineState) (p : Nat) (hpc : s.pc = 0x1000)
    (hx10 : s.getReg .x10 = BitVec.ofNat 64 p) (hal : p % 8 = 0) (hp : p + 48 ≤ 0x20000)
    (fuel : Nat) :
    ∃ t, t.getReg .x11 = 0 ∧ t.pc = 0x10a0 ∧
      Riscv.execute (fuel + 40) image s = (fun e => e.charge 43 0 0) <$> Riscv.execute fuel image t := by
  obtain ⟨t, hst, hpc', -, h11, -⟩ := spec s p hpc hx10 hal hp
  exact ⟨t, h11, hpc', hst.execute fuel⟩

end SigGolfCandidate.Rv.Demo1
