"""Generate SigGolfCandidate/Sign/Code.lean (segment table of the sign image) and
Blocks*.lean (one sym_block per segment) from work/py/out/sign.lst."""
import re, os
LST = '/root/siggolf/work/py/out/sign.lst'
OUT = os.path.dirname(os.path.abspath(__file__))
ins, labels = [], {}
for line in open(LST):
    m = re.match(r'^([A-Za-z_0-9]+):\s*$', line)
    if m:
        labels.setdefault(len(ins), []).append(m.group(1)); continue
    m = re.match(r'^\s+(\d+) ([0-9a-f]{8})  (\S+)(.*)$', line)
    if m:
        assert int(m.group(1)) == len(ins)
        ins.append((m.group(2), m.group(3), m.group(4).strip()))
N = len(ins)
segs = []   # (start, end exclusive)
cur = 0
for i, (w, mn, ops) in enumerate(ins):
    if i > cur and i in labels:
        segs.append((cur, i)); cur = i
    if mn in ('beq', 'bne', 'blt', 'bge', 'bltu', 'bgeu', 'jal', 'ecall', 'jalr'):
        segs.append((cur, i + 1)); cur = i + 1
if cur < N:
    segs.append((cur, N))
assert segs[0][0] == 0 and all(segs[k][1] == segs[k+1][0] for k in range(len(segs)-1)) and segs[-1][1] == N
def name(k): return 'seg%d' % segs[k][0]
L = ['-- Generated by SigGolfCandidate/Sign/gen_code.py from work/py/out/sign.lst. Do not edit.',
     'import SigGolfCandidate.Sign.Base', 'import SigGolfCandidate.Submission', '',
     'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '',
     'set_option maxRecDepth 16384', '']
for k, (a, b) in enumerate(segs):
    lab = ','.join(sum((labels.get(i, []) for i in range(a, b)), []))
    L.append('/-- instructions %d .. %d%s: %s -/' % (a, b - 1, (' (' + lab + ')') if lab else '',
             '; '.join(ins[i][1] + ' ' + ins[i][2] for i in range(a, min(b, a + 6))) + (' ...' if b - a > 6 else '')))
    L.append('def %s : List (BitVec 32) := [%s]' % (name(k), ', '.join('0x%s#32' % ins[i][0] for i in range(a, b))))
L.append('')
L.append('/-- Segment table of the sign image. -/')
L.append('def L : Rv.Layout := [' + ', '.join('(%d, %s)' % (a, name(k)) for k, (a, b) in enumerate(segs)) + ']')
L.append('''
theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The sign image. -/
abbrev image : Image := Images.signImage

theorem image_eq : submission.image .sign = image := rfl

set_option maxHeartbeats 4000000 in
theorem code_eq : image.code = layoutCode L := by decide +kernel
''')
for k, (a, b) in enumerate(segs):
    L.append('theorem codeAt_%d : CodeAt image (pcOf %d) %s :=\n  codeAt_layout code_eq layout_ok (i := %d) (by kernel_rfl) (by decide)' % (a, a, name(k), k))
L += ['', 'end SigGolfCandidate.Sign', '']
open(os.path.join(OUT, 'Code.lean'), 'w').write('\n'.join(L))
# blocks: main program (non-pack) and pack in separate files
main = [(k, s) for k, s in enumerate(segs) if s[0] < min(i for i, ls in labels.items() if 'pack_0' in ls)]
pack = [(k, s) for k, s in enumerate(segs) if (k, s) not in main]
def blocks(fn, lst, header):
    B = ['-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.', 'import SigGolfCandidate.Sign.Code', '',
         'namespace SigGolfCandidate.Sign', 'open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv', '', header, '']
    for k, (a, b) in lst:
        B.append('sym_block blk%d := symRun { noAlias := true } %s (pcOf %d) %d' % (a, name(k), a, b - a + 1))
    B += ['', 'end SigGolfCandidate.Sign', '']
    open(os.path.join(OUT, fn), 'w').write('\n'.join(B))
blocks('Blocks.lean', main, '/-! Symbolic blocks of the sign program (before the pack). -/')
chunks = [pack[i:i + 30] for i in range(0, len(pack), 30)]
for ci, ch in enumerate(chunks):
    blocks('PackBlocks%d.lean' % ci, ch, '/-! Symbolic blocks of the pack. -/')
print(len(segs), 'segments;', len(main), 'main;', len(pack), 'pack in', len(chunks), 'files')
for k, (a, b) in main:
    print(a, b, labels.get(a, ''), ins[b-1][1], ins[b-1][2])
