# Generates SigGolfCandidate/Keygen/Blocks.lean (segment table + symbolic blocks of the keygen image).
import re
src=open("/root/siggolf/work/rv/SigGolfCandidate/Images.lean").read()
m=re.search(r"def keygenCode_0 : List \(BitVec 32\) := \[(.*?)\]",src,re.S)
words=[w.strip() for w in m.group(1).replace("\n"," ").split(",")]
assert len(words)==102
cuts=[0,23,30,34,35,38,42,43,48,57,61,62,64,65,73,88,89,91,93,101,102]
segs=[(cuts[i],cuts[i+1]) for i in range(len(cuts)-1)]
ecalls={34,42,61,88,101}
out=['''import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (34, 42, 61, 88, 101) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192
''']
for a,b in segs:
    out.append(f"def seg_{a} : List (BitVec 32) := [{', '.join(words[a:b])}]")
out.append("\ndef L : Rv.Layout := [" + ", ".join(f"({a}, seg_{a})" for a,b in segs) + "]")
out.append('''
theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel
''')
for i,(a,b) in enumerate(segs):
    out.append(f"theorem codeAt_{a} : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * {a})) seg_{a} :=\n  codeAt_layout code_eq layout_ok (i := {i}) (by kernel_rfl) (by decide)")
out.append("")
for a,b in segs:
    if a in ecalls: continue
    out.append(f"sym_block blk_{a} := symRun {{ noAlias := true }} seg_{a} (BitVec.ofNat 64 (0x1000 + 4 * {a})) 100")
open("/root/siggolf/work/rv/SigGolfCandidate/Keygen/Blocks.lean","w").write("\n".join(out)+"\n\nend SigGolfCandidate.Keygen\n")
