"""Emit the masked keygen and sign images without replacing the submitted ones."""

from pathlib import Path

from examples.sphincs.build_images import build_keygen
from examples.sphincs.sign_image import build_sign


def emit_image(name: str, words: list[int]) -> list[str]:
    chunks = [words[i:i + 96] for i in range(0, len(words), 96)]
    names = [f"{name}Chunk{i}" for i in range(len(chunks))]
    lines: list[str] = []
    for chunk_name, chunk in zip(names, chunks):
        lines.append(f"private def {chunk_name} : List (BitVec 32) := [")
        for start in range(0, len(chunk), 8):
            row = chunk[start:start + 8]
            suffix = "," if start + 8 < len(chunk) else "]"
            lines.append("  " + ", ".join(f"0x{word:08x}" for word in row) + suffix)
        lines.extend([
            "",
            f"private theorem {chunk_name}_length : {chunk_name}.length = {len(chunk)} := by rfl",
            "",
        ])
    lines.extend([
        f"def {name} : Riscv.Image where",
        "  code := " + " ++\n    ".join(names),
        "  data := []",
        "",
        f"theorem {name}_code_length : {name}.code.length = {len(words)} := by",
        "  change (" + " ++ ".join(names) + f").length = {len(words)}",
        "  simp only [List.length_append, " +
        ", ".join(chunk_name + "_length" for chunk_name in names) + "]",
        "",
    ])
    return lines


def main() -> None:
    images = {"keygen": build_keygen(), "sign": build_sign()}
    lines = [
        "-- Generated by examples/sphincs/emit_candidate.py.",
        "import SigGolf",
        "",
        "namespace SigGolfCandidate.SphincsMaskedImages",
        "open SigGolf",
        "set_option maxRecDepth 16384",
        "",
    ]
    for name, words in images.items():
        lines.extend(emit_image(name, words))
        print(name, len(words), "instructions,", 4 * len(words), "image bytes")
    lines.append("end SigGolfCandidate.SphincsMaskedImages")
    target = Path(__file__).resolve().parents[2] / "prototype-images/SphincsMaskedImages.lean"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n")
    print(target)


if __name__ == "__main__":
    main()
